### ISSUE TITLE
user-accounts is not working with Seneca versions later then 0.6.2

### ISSUE THREAD

**Issue by KristinaMatuleviciute** [rjrodger/seneca-examples#36]
u.register({nick: 'u1', name: 'nu1', email: 'u1@example.com', password: 'u1', active: true})
  ^

TypeError: u.register is not a function
    at Object.<anonymous> (/Users/kristina/Desktop/seneca-examplesMy/user-accounts/app.js:79:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
