### ISSUE TITLE
api-server is not working with Seneca versions later then 0.6.2

### ISSUE THREAD

**Issue by KristinaMatuleviciute** [rjrodger/seneca-examples#37]
Message: seneca: Ready function failed: this.make$ is not a function.
When I adding seneca.use('entity') I am getting errors running client.js 

get /hello 200 {"msg":"hello!"}
get /product 500 {"error":"Error: seneca: No matching action pattern found for { base: '-',  method: 'get',  name: 'Seneca/2.1.0/lir29mu39dmf/1464779505386/3004/-',  prefix: '/',  role: 'jsonrest-api',  zone: '-',  kind: 'product',  id: 'lir29mu39dmf/1464779505386/3004/-',  q: {},  did: '(5sryxctocx07)',  toString: [Function],  fixedargs:    { 'req$':       IncomingMessage {        _readableState: [Object],        readable: true,        domain: null,        _events: {},        _eventsCount: 0,        _maxListeners: undefined,        socket: [Object],        connection: [Object],        httpVersionMajor: 1,        httpVersionMinor: 1,        httpVersion: '1.1',        complete: true,        headers: [Object],        rawHeaders: [Object],        trailers: {},        rawTrailers: [],        upgrade: false,        url: '/product',        method: 'GET',        statusCode: null,        statusMessage: null,        client: [Object],        _consuming: false,        _dumped: false,        next: [Function: next],        baseUrl: '',        originalUrl: '/product',        _parsedUrl: [Object],        params: [Object],        query: {},        res: [Object],        body: {},        seneca: [Object],        _route_index: 0 },     'res$':       ServerResponse {        domain: null,        _events: [Object],        _eventsCount: 1,        _maxListeners: undefined,        output: [],        outputEncodings: [],        outputCallbacks: [],        outputSize: 0,        writable: true,        _last: false,        chunkedEncoding: false,        shouldKeepAlive: false,        useChunkedEncodingByDefault: true,        sendDate: true,        _removedHeader: {},        _contentLength: null,        _hasBody: true,        _trailer: '',        finished: false,    ........get /product/0/star 400 {"why":"Bad input."}
put /product/0/star 400 {"why":"Bad input."}
get /product/0/star 400 {"why":"Bad input."}
