### ISSUE TITLE
micro-services is not working with Seneca versions later then 0.6.2 

### ISSUE THREAD

**Issue by KristinaMatuleviciute** [rjrodger/seneca-examples#38]
Message: seneca: Action init:user failed: seneca.make is not a function.

When I adding .use('entity') in user-details.js 

equire('seneca')()
  .use('user')
  .use('entity')
  .listen(10201)
  .ready(function () {
    this.act({role: 'user', cmd: 'register', nick: 'user', name: 'user', password: 'user'})
  })
and in web-app.js,
seneca
  .use('user')
  .use('auth')
  .use('entity')
  .use('../lib/api.js')
 no more errors but login  is not working.
Is it right place I am adding it?

**Comment by sp3897** [comment]
Hi

Did you try updating the dependencies to the following ?

"dependencies": {
"express": "~4.13.4",
"body-parser": "~1.15.1",
"cookie-parser": "~1.4.2",
"method-override": "~2.3.6",
"express-session": "~1.13.0",
"serve-static": "~1.10.2",
"optimist": "~0.6.1",
"ejs": "~2.4.1",
"ejs-locals": "~1.0.2",
"seneca": "0.6.2",
"seneca-user": "~1.0.1",
"seneca-auth": "~1.0.1",
"seneca-admin": "~0.2.0",
"seneca-jsonrest-api": "~0.3.1",
"seneca-perm": "~0.5.6",
"seneca-data-editor": "~0.2.0"
}

Thanks
Surendra

**Comment by KristinaMatuleviciute** [comment]
yes, its working with Seneca 0.6.2, but not working with any of newer versions :)
